# Generated by Django 5.0.2 on 2025-07-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("user", "User"),
                    ("guest", "Guest"),
                    ("moderator", "Moderator"),
                    ("superadmin", "Superadmin"),
                ],
                default="user",
                max_length=20,
            ),
        ),
    ]
