# Generated by Django 5.0.2 on 2025-07-06 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_fileeventlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileeventlog",
            name="file",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="logs", to="chat.fileupload"
            ),
        ),
    ]
